export const mockTMDBData = {
  dates: {
    maximum: "2025-09-17",
    minimum: "2025-08-27",
  },
  page: 1,
  results: [
    {
      adult: false,
      backdrop_path: "/jvpkBenB6hv19WWYVlaiow8zklq.jpg",
      genre_ids: [16, 10751, 35, 80, 12],
      id: 1175942,
      original_language: "en",
      original_title: "The Bad Guys 2",
      overview:
        "The now-reformed Bad Guys are trying (very, very hard) to be good, but instead find themselves hijacked into a high-stakes, globe-trotting heist, masterminded by a new team of criminals they never saw coming: The Bad Girls.",
      popularity: 315.8297,
      poster_path: "/26oSPnq0ct59l07QOXZKyzsiRtN.jpg",
      release_date: "2025-07-24",
      title: "The Bad Guys 2",
      video: false,
      vote_average: 7.9,
      vote_count: 228,
    },
    {
      adult: false,
      backdrop_path: "/1RgPyOhN4DRs225BGTlHJqCudII.jpg",
      genre_ids: [16, 28, 14, 53],
      id: 1311031,
      original_language: "ja",
      original_title: "劇場版「鬼滅の刃」無限城編 第一章 猗窩座再来",
      overview:
        "The Demon Slayer Corps are drawn into the Infinity Castle, where Tanjiro, Nezuko, and the Hashira face terrifying Upper Rank demons in a desperate fight as the final battle against Muzan Kibutsuji begins.",
      popularity: 301.8484,
      poster_path: "/aFRDH3P7TX61FVGpaLhKr6QiOC1.jpg",
      release_date: "2025-07-18",
      title: "Demon Slayer: Kimetsu no Yaiba Infinity Castle",
      video: false,
      vote_average: 7.1,
      vote_count: 91,
    },
    {
      adult: false,
      backdrop_path: "/qEFTuoFIAwrnVn7IsvE8RVt2TK3.jpg",
      genre_ids: [14, 10751, 28, 12],
      id: 1087192,
      original_language: "en",
      original_title: "How to Train Your Dragon",
      overview:
        "On the rugged isle of Berk, where Vikings and dragons have been bitter enemies for generations, Hiccup stands apart, defying centuries of tradition when he befriends Toothless, a feared Night Fury dragon. Their unlikely bond reveals the true nature of dragons, challenging the very foundations of Viking society.",
      popularity: 206.9023,
      poster_path: "/q5pXRYTycaeW6dEgsCrd4mYPmxM.jpg",
      release_date: "2025-06-06",
      title: "How to Train Your Dragon",
      video: false,
      vote_average: 8.027,
      vote_count: 1737,
    },
    {
      adult: false,
      backdrop_path: "/2VGfjnT3RpjOKADbwgbmXCFSbH.jpg",
      genre_ids: [27, 53],
      id: 1443260,
      original_language: "en",
      original_title: "Rob1n",
      overview:
        "When a robotics expert channels the grief of losing his 11 year-old son into building 'Robin', a fully functioning robotic doll, a series of horrific events makes it clear Robin will do whatever it takes to have his creator all to himself.",
      popularity: 131.9568,
      poster_path: "/5lJ2ftNE18iYGCdOQsQirzHHtnX.jpg",
      release_date: "2025-03-20",
      title: "Rob1n",
      video: false,
      vote_average: 5.197,
      vote_count: 33,
    },
    {
      adult: false,
      backdrop_path: "/9whEVuKte4Qi0LI4TzPf7glinJW.jpg",
      genre_ids: [16, 10751, 14],
      id: 936108,
      original_language: "en",
      original_title: "Smurfs",
      overview:
        "When Papa Smurf is mysteriously taken by evil wizards, Razamel and Gargamel, Smurfette leads the Smurfs on a mission into the real world to save him. With the help of new friends, the Smurfs must discover what defines their destiny to save the universe.",
      popularity: 116.28,
      poster_path: "/8o6lkhL32xQJeB52IIG1us5BVey.jpg",
      release_date: "2025-07-05",
      title: "Smurfs",
      video: false,
      vote_average: 6.1,
      vote_count: 132,
    },
    {
      adult: false,
      backdrop_path: "/c9xmB53umjnrCMS4pZz11clF3yJ.jpg",
      genre_ids: [16, 14, 12, 28],
      id: 980477,
      original_language: "zh",
      original_title: "哪吒之魔童闹海",
      overview:
        "After a catastrophic event leaves their bodies destroyed, Ne Zha and Ao Bing are granted a fragile second chance at life. As tensions rise between the dragon clans and celestial forces, the two must undergo a series of perilous trials that will test their bond, challenge their identities, and decide the fate of both mortals and immortals.",
      popularity: 123.5282,
      poster_path: "/cb5NyNrqiCNNoDkA8FfxHAtypdG.jpg",
      release_date: "2025-01-29",
      title: "Ne Zha 2",
      video: false,
      vote_average: 8,
      vote_count: 318,
    },
    {
      adult: false,
      backdrop_path: "/7Q2CmqIVJuDAESPPp76rWIiA0AD.jpg",
      genre_ids: [28, 12, 18],
      id: 1011477,
      original_language: "en",
      original_title: "Karate Kid: Legends",
      overview:
        "After a family tragedy, kung fu prodigy Li Fong is uprooted from his home in Beijing and forced to move to New York City with his mother. When a new friend needs his help, Li enters a karate competition – but his skills alone aren't enough. Li's kung fu teacher Mr. Han enlists original Karate Kid Daniel LaRusso for help, and Li learns a new way to fight, merging their two styles into one for the ultimate martial arts showdown.",
      popularity: 110.6501,
      poster_path: "/AEgggzRr1vZCLY86MAp93li43z.jpg",
      release_date: "2025-05-08",
      title: "Karate Kid: Legends",
      video: false,
      vote_average: 7.139,
      vote_count: 744,
    },
    {
      adult: false,
      backdrop_path: "/ijRF7DuzDoM52Azt1eC271ecbjn.jpg",
      genre_ids: [28, 80, 53],
      id: 1419406,
      original_language: "zh",
      original_title: "捕风追影",
      overview:
        "Macau Police brings the tracking expert police officer out of retirement to help catch a dangerous group of professional thieves.",
      popularity: 85.5029,
      poster_path: "/wXeAsIkA7k9YVk0JEwPjjkqZwx8.jpg",
      release_date: "2025-08-16",
      title: "The Shadow's Edge",
      video: false,
      vote_average: 7.5,
      vote_count: 15,
    },
    {
      adult: false,
      backdrop_path: "/2DcD4Hh80SW7YVpwckkiEFRZX06.jpg",
      genre_ids: [28, 35],
      id: 1124619,
      original_language: "en",
      original_title: "Bride Hard",
      overview:
        "Sam is a secret agent whose toughest mission to date is pleasing her bride-to-be best friend at a lavish destination wedding. When a team of mercenaries crashes the party and takes the guests hostage, Sam is thrown into a fight unlike any before — one where she can’t risk blowing her cover or ruining the big day. As she takes on the bad guys in a high-stakes battle disguised as a fairy-tale affair, she realizes the real threat might be closer than she thinks.",
      popularity: 58.1836,
      poster_path: "/3mExdWLSxAiUCb4NMcYmxSkO7n4.jpg",
      release_date: "2025-06-19",
      title: "Bride Hard",
      video: false,
      vote_average: 5.716,
      vote_count: 88,
    },
    {
      adult: false,
      backdrop_path: "/dcLV5rEXuQRW0ZlB7IMLArHMyWh.jpg",
      genre_ids: [35, 14, 10751],
      id: 1125257,
      original_language: "en",
      original_title: "Freakier Friday",
      overview:
        "Years after Tess and Anna endured an identity crisis, Anna now has a daughter of her own and a soon-to-be stepdaughter. As they navigate the myriad challenges that come when two families merge, Tess and Anna discover lightning might indeed strike twice.",
      popularity: 59.8626,
      poster_path: "/9wV65OmsjLAqBfDnYTkMPutXH8j.jpg",
      release_date: "2025-08-06",
      title: "Freakier Friday",
      video: false,
      vote_average: 6.933,
      vote_count: 127,
    },
    {
      adult: false,
      backdrop_path: "/wO15XEgeLbeijtf3MQAUqWCxSxc.jpg",
      genre_ids: [28, 53],
      id: 1007734,
      original_language: "en",
      original_title: "Nobody 2",
      overview:
        "Former assassin Hutch Mansell takes his family on a nostalgic vacation to a small-town theme park, only to be pulled back into violence when they clash with a corrupt operator, a crooked sheriff, and a ruthless crime boss.",
      popularity: 55.8585,
      poster_path: "/iyxwxDZCpIm0vIORaHpmgJv2BGF.jpg",
      release_date: "2025-08-13",
      title: "Nobody 2",
      video: false,
      vote_average: 7.308,
      vote_count: 99,
    },
    {
      adult: false,
      backdrop_path: "/lqwwGkwJHtz9QgKtz4zeY19YgDg.jpg",
      genre_ids: [10749, 18],
      id: 1136867,
      original_language: "en",
      original_title: "Materialists",
      overview:
        "A young, ambitious New York City matchmaker finds herself torn between the perfect match and her imperfect ex.",
      popularity: 50.6896,
      poster_path: "/eDo0pNruy0Qgj6BdTyHIR4cxHY8.jpg",
      release_date: "2025-06-12",
      title: "Materialists",
      video: false,
      vote_average: 6.741,
      vote_count: 432,
    },
    {
      adult: false,
      backdrop_path: "/5PJkK2iVXRO1ydrtgwuJdevmnOe.jpg",
      genre_ids: [37, 35, 80],
      id: 648878,
      original_language: "en",
      original_title: "Eddington",
      overview:
        "In May of 2020, a standoff between a small-town sheriff and mayor sparks a powder keg as neighbor is pitted against neighbor in Eddington, New Mexico.",
      popularity: 41.2864,
      poster_path: "/kg7lrTWGKyzLnj0E7BXl52nro1N.jpg",
      release_date: "2025-07-16",
      title: "Eddington",
      video: false,
      vote_average: 6.5,
      vote_count: 193,
    },
    {
      adult: false,
      backdrop_path: "/eNSUknQqzTXWE5EeT8ZnVccEPR0.jpg",
      genre_ids: [27, 53],
      id: 1285965,
      original_language: "en",
      original_title: "Dangerous Animals",
      overview:
        "A savvy and free-spirited surfer is abducted by a shark-obsessed serial killer. Held captive on his boat, she must figure out how to escape before he carries out a ritualistic feeding to the sharks below.",
      popularity: 41.9636,
      poster_path: "/9tk3Si960hg4E49eMt81dS7Qe9Z.jpg",
      release_date: "2025-06-05",
      title: "Dangerous Animals",
      video: false,
      vote_average: 6.534,
      vote_count: 190,
    },
    {
      adult: false,
      backdrop_path: "/1KwliRKTw61fRGmbG4Sf8eWOHP.jpg",
      genre_ids: [28, 35, 80],
      id: 1181540,
      original_language: "en",
      original_title: "Guns Up",
      overview:
        "When a job goes horribly wrong, an ex-cop and family man who moonlights as a mob henchman has one night to get his family out of the city.",
      popularity: 40.6208,
      poster_path: "/3RokBWEkQqJRZEVP3DPwGm5MYh6.jpg",
      release_date: "2025-05-15",
      title: "Guns Up",
      video: false,
      vote_average: 6.867,
      vote_count: 75,
    },
    {
      adult: false,
      backdrop_path: "/vgnoBSVzWAV9sNQUORaDGvDp7wx.jpg",
      genre_ids: [12, 18, 878],
      id: 157336,
      original_language: "en",
      original_title: "Interstellar",
      overview:
        "The adventures of a group of explorers who make use of a newly discovered wormhole to surpass the limitations on human space travel and conquer the vast distances involved in an interstellar voyage.",
      popularity: 42.7807,
      poster_path: "/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg",
      release_date: "2014-11-05",
      title: "Interstellar",
      video: false,
      vote_average: 8.46,
      vote_count: 37709,
    },
    {
      adult: false,
      backdrop_path: "/9DYFYhmbXRGsMhfUgXM3VSP9uLX.jpg",
      genre_ids: [27],
      id: 1038392,
      original_language: "en",
      original_title: "The Conjuring: Last Rites",
      overview:
        "A sequel to The Conjuring: The Devil Made Me Do It. Paranormal investigators Ed and Lorraine Warren take on one last terrifying case involving mysterious entities they must confront.",
      popularity: 36.9734,
      poster_path: "/vufNNzDaMZMTBkzSDDV2PmLURjW.jpg",
      release_date: "2025-09-03",
      title: "The Conjuring: Last Rites",
      video: false,
      vote_average: 0,
      vote_count: 0,
    },
    {
      adult: false,
      backdrop_path: "/1wi1hcbl6KYqARjdQ4qrBWZdiau.jpg",
      genre_ids: [35, 80, 28],
      id: 1035259,
      original_language: "en",
      original_title: "The Naked Gun",
      overview:
        "Only one man has the particular set of skills... to lead Police Squad and save the world: Lt. Frank Drebin Jr.",
      popularity: 33.095,
      poster_path: "/rmwQ8GsdQ1M3LtemNWLErle2nBU.jpg",
      release_date: "2025-07-30",
      title: "The Naked Gun",
      video: false,
      vote_average: 6.907,
      vote_count: 246,
    },
    {
      adult: false,
      backdrop_path: "/eQV9rSQ6S1ja4lGTwHTnQuVhoG.jpg",
      genre_ids: [27, 35, 14, 18],
      id: 1284120,
      original_language: "no",
      original_title: "Den stygge stesøsteren",
      overview:
        "In a fairy-tale kingdom where beauty is a brutal business, Elvira battles to compete with her incredibly beautiful stepsister, and she will go to any length to catch the prince’s eye.",
      popularity: 28.2994,
      poster_path: "/crX9rSg9EohybhkEe8iTQUCe55y.jpg",
      release_date: "2025-03-07",
      title: "The Ugly Stepsister",
      video: false,
      vote_average: 7.235,
      vote_count: 325,
    },
    {
      adult: false,
      backdrop_path: "/fBlzTwgtbDYkDKlhnPu69jHfVGy.jpg",
      genre_ids: [27, 10749],
      id: 1242011,
      original_language: "en",
      original_title: "Together",
      overview:
        "With a move to the countryside already testing the limits of a couple's relationship, a supernatural encounter begins an extreme transformation of their love, their lives, and their flesh.",
      popularity: 29.5524,
      poster_path: "/m52XidzKx94bKlToZfEXUnL3pdy.jpg",
      release_date: "2025-07-23",
      title: "Together",
      video: false,
      vote_average: 7.3,
      vote_count: 214,
    },
  ],
  total_pages: 64,
  total_results: 1274,
}
